construct/construct

- construct/lib/container.py
- tests/test_search.py
As discussed here: https://groups.google.com/forum/#!topic/construct3/7abbfuCGAUI
I added *search* and *search_all* for searching specific tags inside containers. *search* only returns the first occurrence, *search_all* returns all of them.
This should allow users to easily check their Constructs for specific data.
I've implemented some basic tests, they probably dont cover all of the end-cases so if you see anything thats missing, let me know.
As a side note, it could be interesting adding something similar to XPath for more sophisticated searches as done here: http://docs.python.org/2/library/xml.etree.elementtree.html#elementtree-xpath
> Search functionality for containers

- construct/lib/bitstream.py
These classes use `__slots__`, however they are defined as old style classes (not subclassing object) in which `__slots__` has no effect. The classes should either remain old style classes and not use `__slots__`, or they should be new style classes.
> The IO classes in construct.lib.bitstream should be new style classes

- construct/lib/bitstream.py
- tests/test_all.py
Prior to 3cb79d89a61510dd8d63816bb32380e7e1a2b1c9 it was possible to use `Peek` in the subconstruct of `Prefixed`, however with the introduction of `BoundBytesIO` using `Peek` will generate an exception
```python
AttributeError: BoundBytesIO instance has no attribute 'seek'
```
This PR adds the seek functionality to `BoundBytesIO` and re-enables the use of `Peek` in a prefixed `Subconstruct`.
> Fix the use of Peek in a Prefixed Subconstruct

- construct/lib/container.py
- tests/lib/test_container.py
Reset explicitly all state-related variables and apply the supplied state.
Also add an inner Container to the pickling test.
This should fix #249.
> Fix pickling

- construct/debug.py
Running the manual debugger test gives the following output
```
python tests/manual_debug.py
Container:
bar = 1
spam = DEF
eggs = 3
================================================================================
Debugging exception of <Renamed: spam>:
Traceback (most recent call last):
File "/home/beardypig/construct/construct/core.py", line 2768, in _decode
return self.decoding[obj]
KeyError: 4
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/beardypig/construct/construct/core.py", line 2696, in _parse
return self.subcon._parse(stream, context, path)
File "/home/beardypig/construct/construct/core.py", line 313, in _parse
return self._decode(self.subcon._parse(stream, context, path), context)
File …
```
> Bug fix for Debugger, fixes NameError

- construct/lib/container.py
- tests/lib/test_container.py
Explicitly use `object` or `dict` methods for getting attributes. This keeps
the `__slots__` as `object` attributes and everything else as part of the
`dict` instance.
Pickle can then automatically takes care of the `dict` and the only
relevant slot (`__keys_order__`) is saved. No need to update a
dictionary with the items it already has.
This should address at least the pickling part of #249 .
I've removed the expected fail from the test suite. This should pass for all supported Python versions before being merged.
> Fix pickling in Python 2 and 3

- construct/core.py
- construct/examples/formats/data/cap.py
Exceptions are hidden when building a Range object. I was having some problems debugging until I worked it out :)
> Don't hide Exceptions in Range._build

- construct/expr.py
- docs/meta.rst
- tests/test_this.py
This enables the use of [] to get items from this.
e.g.
```this["item with space and punctuation in it's name!"]```
Closes #276
> Add __getitem__ to Path for the this expression.

- construct/core.py
In Python 2.7, file objects do not return the number of bytes written.
> fix python2 compatibility

- construct/examples/formats/graphics/png.py
Without this patch, the process of parsing docs/_static/construct-logo.png will stop after the first tEXt chunk.
> fix png chunk field length

- construct/core.py
- tests/test_all.py
Commit 4836722 implements a `RepeatUntil` with an extra current-list argument.
This fails when building, as the list is always complete.
A solution is to take a partial list as subconstructs are built.
This PR implements both the solution and an extra test.
> Fix building for RepeatUntil with list

- tox.ini
i.e. --lf to run only last failures, or -s that let the
Debugger in construct work.
> Add posargs to tox to be able to pass more args to pytest

- construct/core.py
The class that has a byte-length field before the data is
construct.core.Prefixed and not construct.core.Array
> Prefixed instead of Array

- construct/core.py
- Removed unnecessary `__init__` methods
- Removed unused variable `length` in `StringPaddedTrimmed._decode`
- Rewrote lambda + filter to list comprehension.
- Made it clear that we are intentionally only using the values of the Enum mapping while iterating.
- Removed unused `enumerate` calls
> Other linter complaints

- docs/meta.rst
Brings it in line with changes made in https://github.com/construct/construct/commit/2a615c597f5a21aaa40e7869a085ba5ea56467d6
> Adding missing parameter to `PrintContext` in docs

- .gitignore
Add .tox to .gitignore to ensure it will never be added
> Tune .gitignore to ignore .tox directory

- construct/examples/protocols/ipstack.py
I use the `layer3_ipv4` in my app and discovered that properly tested ICMP protocol is not used anywhere except the test suite.
Before:
```
ipv4 = Container: 
header = Container: 
version = 4
header_length = 20
tos = Container: 
precedence = 0
minimize_delay = False
high_throuput = False
high_reliability = False
minimize_cost = False
total_length = 60
payload_length = 40
identification = 7126
flags = Container: 
dont_fragment = False
more_fragments = False
frame_offset = 0
ttl = 128
protocol = ICMP (total 4)
checksum = 62945
source = 13.0.253.232 (total 12)
destination = 12.0.18.33 (total 10)
options =  (total 0)
next = None
```
After:
```
ipv4 = Container: 
header = Container: 
version = 4
header_length = 20
tos = Container: 
precedence = 0
minimize_delay = False
high_throuput = False …
```
> Example ipstack: Add missing ICMP payload

- construct/examples/formats/__init__.py
- construct/examples/formats/executable/pe32.py
- tests/examples/test_formats.py
The pe32 example format doesn't work in construct 2.8.
I think I've adapted it properly. It works for my simple tests at least :)
> get pe32 working again

- construct/expr.py
- tests/test_all.py
- tests/test_this.py
The `<<` operator acts like the `>>` operator in certain cases.
```python
>>> from construct import *
>>> Test = Struct(
...    "a_byte" / Byte,
...    "test_rshift" / Computed(this["a_byte"] >> 1),
...    "test_lshift" / Computed(this["a_byte"] << 1),
... )
>>> Test.parse(b"\x01")
Container(a_byte=1)(test_rshift=0)(test_lshift=0)
```
The operator overloads for `__lshift__` and `__rlshift__` in `construct/expr.py` call `operator.rshift` where they should call `operator.lshift`. 
After replacing these, things work as expected:
```python
>>> from construct import *
>>> Test = Struct(
...    "a_byte" / Byte,
...    "test_rshift" / Computed(this["a_byte"] >> 1),
...    "test_lshift" / Computed(this["a_byte"] << 1),
... )
>>> Test.parse(b"\x01") …
```
> FIX: Left-shift operator

- tests/test_all.py
Add the missing assertions for bug https://github.com/construct/construct/issues/298
Only assertions for parsing were added but the bug was in building.
I suspect that the bug originates in this change: https://github.com/construct/construct/commit/489c78c23fde24b959559b47c492cd1234494252#commitcomment-25640446
(Regarding the failed check in CI - this is expected due to adding the failing assertion)
> add the missing assertions to test_from_issue_298

- .travis.yml
Due to a spelling mistake, the Travis e-mail notification settings weren’t properly configured. This fixes the spelling error, which should make the Travis notifications work again for @arekbulski.
> Fix Travis e-mail notifications

- construct/core.py
Enable referencing a Mapping and Enum names as attributes of the created objects.
Example:
`assert Enum(Byte, one=1).one == 'one'`
Partially solves #597
> Enum to contain members holding string names

- construct/core.py
The current `FlagsEnum` implementation doesn't handle flag values that have multiple bits set.
For instance, take the `IMAGE_SCN_ALIGN_64BYTES` flag (0x00700000) from the PE specification. Setting this flag will make the current implementation think that `IMAGE_SCN_ALIGN_8192BYTES` (0x00E00000) is also set, which is clearly incorrect.
> Add support for multi-bit flags

- construct/lib/containers.py
- tests/test_core.py
`Hex()` didn't work when used with `Bytes()` within `Struct()`.
> Fix issue #709: Hex() might not always work.

- docs/basics.rst
See #719 
I also added a note that exceptions inside the function are silently dropped. When I used the code `ctx._._index` I saw no output of the function. Then I found out that there is no output as the exception was dropped.
> docs: fix _index and add note about exception handling

- .travis.yml
Fixed minor warnings (sudo, os), ident 2 spaces, replaced 3.7-dev to stable 3.7.
According to https://issues.apache.org/jira/browse/ARROW-2100 arrow dropped python 3.4 support. While construct still runnable under 3.4, testing cannot be done.
> Fixes to .travis.yml

- .github/workflows/main.yml
Enabling Github Actions for CI testing. Supported versions:
* Python 3.5 - 3.8
* PyPy2 and PyPy3
> Enabling GitHub actions as Travis drop in

- tests/test_core.py
Example for issue #781: Refering to inlined constructs in BitStruct
> add testcase (marked as xfail) for issue #781

- construct/core.py
- tests/test_core.py
Right now, when building `Struct("opt" / Optional)`, the key `opt` must be specified, even if its value is `None`.
There's been a couple issues about this, I've read the response in #710 in particular. I understand why the behavior of `Optional` is as described above, but ISTM it doesn't _need_ to be that way.
Given that the code change is actually very simple, and it seems technically correct, I went ahead and made a PR.
Rationale: `Optional` is equal to `Select(subcon, Pass)`, so there is no practical difference between sending `None` to subcon explicitly and having it fail, and sending `None` implicitly when no value is provided. So technically speaking, `flagbuildnone` is true for this particular form of `Select` even in cases when it is false for subcon.
(if the subcon would instead …
> allow Select to build from none if any of its subcons can

- setup.py
This allows `pip` to pick an older version of Construct on Python 3.5 (and 2.7 presumably). Currently pip attempts to download the latest version, which then fails to install.
It would be super nice if you could apply this patch and then unpublish the version(s?) that break python 3.5 compatibility
> add python version requirement to setup.py

- construct/core.py
- tests/declarativeunittest.py
- tests/test_core.py
This is to fix #888.
I can think of two broad approaches to fix this:
1) Require that all streams given to `_build()` are both readable and writeable. In this view, `build_file()` is in error, and is trivial to    adjust. This is the approach I took here.
2) Require that `_build()` methods cannot assume that streams are writeable. Then we could fix this by having `RawCopy._build()` create a memory stream, give that to its subcon, and then write out what is written to its output stream as well as keeping the copy for its data attribute. Done carefully, no additional memory would be required as `RawCopy` by design keeps a copy of all data written out anyway. Having just learned about this library, I'm not sure if there would be other implications I don't know about though.
> build_file() stream reading

- construct/core.py
This caught me out earlier, so I thought it would be useful to document the required way of handling this use case.
> RawCopy docstring: add note about rebuilding

- construct/core.py
- tests/test_core.py
This fixes a bug, when a construct should be copied with `copy.copy(...)`
> fixed __copy__ of construct

- .github/workflows/main.yml
- tests/declarativeunittest.py
- tests/deprecated_gallery/test_formats.py
- tests/deprecated_gallery/test_protocols.py
- tests/gallery/test_gallery.py
- tests/lib/test_binary.py
- tests/lib/test_bitstream.py
- tests/lib/test_containers_dict.py
- tests/lib/test_containers_list.py
- tests/lib/test_hex.py
- tests/lib/test_py3compat.py
- tests/lib/test_search.py
- tests/test_benchmarks.py
- tests/test_compiler.py
- tests/test_core.py
- tests/test_expr.py
- tests/test_multiprocessing.py
With this fix the pytest now also runs on my Windows 10 machine. The main problem is, that `/dev/zero` is not available on Windows.
The second problem is in `test_multiprocessing`, but i have not investigated further and ignored for now. This error message was thrown: 
```
FAILED tests/test_multiprocessing.py::test_multiprocessing - AttributeError: Can't pickle local object 'test_multiprocessing.<locals>.worker'
```
> pytests now also works on windows

- construct/__init__.py
- construct/core.py
This small change helps me both when improving the type hints (from #886) and when creating a GUI (from #903) for construct elements, since I can check via `isinstance` whether the construct is a `TimestampAdapter`.
> Created a base class for local TimestampAdapter's

- .github/workflows/main.yml
- docs/intro.rst
- setup.py
This PR updates the docs and the CI, so that Python 3.10 is official supported. The CI passes without problems for Python 3.10.
> Declare Python 3.10 as official supported

- .github/workflows/main.yml
The update for actions/checkout and actions/setup-python are required, because the old version still rely on Nodejs 12, see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/ for more details.
Python 3.11 is added, because it is released for quite some time now and needs to be ensured that no changes are introduced that break 3.11.
Update: Replaced "pypy3" by "pypy3.9", because actions/setup-python@v4 doesn't accept "pypy3" anymore. The choice of PyPy 3.9 is arbitrary. Not sure which versions should be tested.
Also I made the OS name visible in the job description.
> Update actions and include Python 3.11

- construct/core.py
The decoder and encoder lambdas get passed 2 arguments, not 3 like the documentation said.
> Update documentation for ExprAdapter

- construct/core.py
- tests/test_compiler.py
Union already had this line in its own _emitbuild method and Struct had it in its _build method.
> Fix missing objects in Struct._emitbuild's context

- construct/lib/containers.py
I started using construct, and noticed the parsing performance differences to Kaitai. I then looked for bottlenecks using cProfile, and it looks to me that the creation and handling of `Container` instances is probably at the center of it, especially for compiled structs, where the byte reading operations are not such a large issue anymore.
I wonder if it might give a performance boost to use a class factory/metaclass to create struct-specific container classes with `__slots__` for fields instead of using a dict, but diving into that, to see how and if it can be possible, will take some more time and work.
So for now I rather looked at the low-hanging fruits, and noticed that it should be possible to speed up the `Container` class by using `dict` instead of `collections.OrderedDict` if …
> Use builtin dict in Container for Python >=3.7

- .github/workflows/main.yml
- construct/lib/containers.py
- docs/basics.rst
- tests/lib/test_containers_dict.py
Change `Container` implementation. This implementation is **5x** faster on my machine on CPython3.12.
This is a **backwards incompatible** change:
- **the biggest problem:** shadowing behaviour changed. Before `con.update` was always referring to method, now it will refer to container item called `update` (if it exists, otherwise it will be a method). I added new test to ensure that behaviour. All other container-related tests pass perfectly. Documentation was updated too. There is a couple in the `core.py` that was using methods directly, they probably should be updated to do `Container.method(ctx, ...)`
- `__(get|set|del)attr__` methods were removed. If anybody is calling them directly (`con.__getattr__('foo')`), this code will break
- `Container.update` method was removed. It wasn't …
> change `Container` implementation

- pytest.ini
pytest 8 changed the way how tests get discovered, adding this ini file makes it find the pytests of construct 
This is a very simple change, which should not need a lot of review before accepting/rejecting it.
> - add pytest.ini file to enable pytest 8.x.y to find the tests

- .github/workflows/main.yml
- construct/core.py
- tests/test_core.py
This fixes https://github.com/construct/construct/issues/1065
It adds a dictionary "userfunction" which works the same as linkedbuilders / linkedparsers. This dictionary is used to store the user supplied functions which are then referenced in the compiled construct.
The decission weather or not we have a user supplied function at hand is donne by.:
```python
if isinstance(self.func, ExprMixin) or (not callable(self.func)):
#dont use the userfunction 
else:
#use the userfunction   
```
Rebuild is not the only place where this makes sense. "IfThenElse" and "Switch" can also benefit of this improvement.
> Allow for user supplied functions in compiled mode

- construct/core.py
- tests/test_core.py
This PR adds a new keyword argument called `relativeOffset` to the `Pointer` subconstruct which causes the offset to be interpreted as being relative to the current stream position.
This is quite useful in certain situations, as shown in #1112.
I tried my best regarding `_emitparse` and `_emitbuild`, but i would be very happy if someone knowledgeable would take a look at it.
Thanks,
Armin Wolf
> Allow for interpreting the Pointer offset as relative
